# Generated by Django 3.2.16 on 2022-12-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='house_id',
            new_name='house',
        ),
    ]
