# Generated by Django 3.2.16 on 2022-12-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_house_id_order_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['application_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
